
services:
  backend:
    build:
      context: ./backend
      args:
        INSTALL_DEV: ${INSTALL_DEV:-true}
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  admin-panel:
    build:
      context: ./admin-panel
    ports:
      - "3001:3000"
    volumes:
      - ./admin-panel/src:/app/src

  providers-panel:
    build:
      context: ./providers-panel
    ports:
      - "3002:3000"
    volumes:
      - ./providers-panel/src:/app/src

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  taskiq-worker:
    build:
      context: ./backend
      args:
        INSTALL_DEV: ${INSTALL_DEV:-true}
    depends_on:
      - redis
      - db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    command: ["/bin/bash", "/app/taskiq-worker-start.sh"]

  taskiq-scheduler:
    build:
      context: ./backend
      args:
        INSTALL_DEV: ${INSTALL_DEV:-true}
    depends_on:
      - redis
      - db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    command: ["/bin/bash", "/app/taskiq-scheduler-start.sh"]

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: internal-mono