version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    args:
      INSTALL_DEV: ${INSTALL_DEV:-true}

networks:
  default:
    name: internal-mono