"""make provider_request_id optional in provider table

Revision ID: 0b6fea0ee3b4
Revises: 37422a744e10
Create Date: 2025-08-26 09:03:41.238237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b6fea0ee3b4'
down_revision: Union[str, Sequence[str], None] = '37422a744e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('provider', 'provider_request_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('provider', 'provider_request_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
