"""remove_trip_price_add_package_currency

Revision ID: 11c278849b87
Revises: 487459728ac9
Create Date: 2025-09-03 04:01:15.677872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11c278849b87'
down_revision: Union[str, Sequence[str], None] = '487459728ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    currency_enum = sa.Enum('SAR', name='currency')
    currency_enum.create(op.get_bind())
    
    op.drop_column('trip', 'price')
    op.add_column('trippackage', sa.Column('currency', currency_enum, nullable=False, server_default='SAR'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trippackage', 'currency')
    # Drop the enum type
    sa.Enum(name='currency').drop(op.get_bind())
    op.add_column('trip', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
