"""add_payment_audit_logs_table

Revision ID: 1b57a044cc51
Revises: a529f42af1f7
Create Date: 2026-01-31 16:06:39.412535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '1b57a044cc51'
down_revision: Union[str, Sequence[str], None] = 'a529f42af1f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_audit_logs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('payment_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('moyasar_payment_id', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.Enum('PAYMENT_CREATED', 'PAYMENT_INITIATED', 'PAYMENT_PAID', 'PAYMENT_FAILED', 'PAYMENT_REFUNDED', 'PAYMENT_VOIDED', 'WEBHOOK_RECEIVED', 'WEBHOOK_VERIFIED', 'WEBHOOK_FAILED', 'API_CALL_SUCCESS', 'API_CALL_FAILED', 'STATUS_CHANGED', 'REFUND_REQUESTED', 'REFUND_PROCESSED', name='paymenteventtype'), nullable=False),
    sa.Column('event_description', sa.String(length=500), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_data', sa.JSON(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('webhook_signature', sa.String(length=500), nullable=True),
    sa.Column('webhook_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_audit_logs_created_at'), 'payment_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_audit_logs_event_type'), 'payment_audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_payment_audit_logs_moyasar_payment_id'), 'payment_audit_logs', ['moyasar_payment_id'], unique=False)
    op.create_index(op.f('ix_payment_audit_logs_payment_id'), 'payment_audit_logs', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_audit_logs_user_id'), 'payment_audit_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_audit_logs_user_id'), table_name='payment_audit_logs')
    op.drop_index(op.f('ix_payment_audit_logs_payment_id'), table_name='payment_audit_logs')
    op.drop_index(op.f('ix_payment_audit_logs_moyasar_payment_id'), table_name='payment_audit_logs')
    op.drop_index(op.f('ix_payment_audit_logs_event_type'), table_name='payment_audit_logs')
    op.drop_index(op.f('ix_payment_audit_logs_created_at'), table_name='payment_audit_logs')
    op.drop_table('payment_audit_logs')
    # ### end Alembic commands ###
