"""Make email and phone nullable for mobile users

Revision ID: 231716205940
Revises: 3a8899f762a6
Create Date: 2026-01-20 16:34:25.798903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '231716205940'
down_revision: Union[str, Sequence[str], None] = '3a8899f762a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_trip_end_date'), table_name='trip')
    op.drop_index(op.f('idx_trip_max_participants'), table_name='trip')
    op.drop_index(op.f('idx_trip_name'), table_name='trip', postgresql_ops={'name': 'text_pattern_ops'})
    op.drop_index(op.f('idx_trip_provider_active'), table_name='trip')
    op.drop_index(op.f('idx_trip_start_date'), table_name='trip')
    op.drop_index(op.f('idx_trippackage_price'), table_name='trippackage')
    op.drop_index(op.f('idx_trippackage_trip_active'), table_name='trippackage')
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('idx_trippackage_trip_active'), 'trippackage', ['trip_id', 'is_active'], unique=False)
    op.create_index(op.f('idx_trippackage_price'), 'trippackage', ['price'], unique=False)
    op.create_index(op.f('idx_trip_start_date'), 'trip', ['start_date'], unique=False)
    op.create_index(op.f('idx_trip_provider_active'), 'trip', ['provider_id', 'is_active'], unique=False)
    op.create_index(op.f('idx_trip_name'), 'trip', ['name'], unique=False, postgresql_ops={'name': 'text_pattern_ops'})
    op.create_index(op.f('idx_trip_max_participants'), 'trip', ['max_participants'], unique=False)
    op.create_index(op.f('idx_trip_end_date'), 'trip', ['end_date'], unique=False)
    # ### end Alembic commands ###
