"""add_spot_reserved_until_to_trip_registration

Revision ID: 273c654aef72
Revises: 5cb9c21916df
Create Date: 2026-02-22 00:23:00.597303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273c654aef72'
down_revision: Union[str, Sequence[str], None] = '5cb9c21916df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tripregistration', sa.Column('spot_reserved_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tripregistration', 'spot_reserved_until')
    # ### end Alembic commands ###
