"""add_nationality_to_trip_registration_participant

Revision ID: 2d0f2804bc89
Revises: 65f84c0d6008
Create Date: 2026-03-15 05:18:49.694499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0f2804bc89'
down_revision: Union[str, Sequence[str], None] = '65f84c0d6008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tripregistrationparticipant', sa.Column('nationality', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tripregistrationparticipant', 'nationality')
    # ### end Alembic commands ###
