"""add timestamps to all models and refactor provider request

Revision ID: 39ef452a6f14
Revises: 0b6fea0ee3b4
Create Date: 2025-08-26 09:56:28.234909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39ef452a6f14'
down_revision: Union[str, Sequence[str], None] = '0b6fea0ee3b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('provider', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('providerrequest', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('providerrequest', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_index(op.f('ix_providerrequest_company_email'), table_name='providerrequest')
    op.drop_column('providerrequest', 'company_metadata')
    op.drop_column('providerrequest', 'company_phone')
    op.drop_column('providerrequest', 'company_email')
    op.drop_column('providerrequest', 'company_name')
    op.add_column('trip', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('trip', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('tripregistration', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tripregistration', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('tripregistration', 'updated_at')
    op.drop_column('tripregistration', 'created_at')
    op.drop_column('trip', 'updated_at')
    op.drop_column('trip', 'created_at')
    op.add_column('providerrequest', sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('providerrequest', sa.Column('company_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('providerrequest', sa.Column('company_phone', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('providerrequest', sa.Column('company_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_providerrequest_company_email'), 'providerrequest', ['company_email'], unique=True)
    op.drop_column('providerrequest', 'updated_at')
    op.drop_column('providerrequest', 'created_at')
    op.drop_column('provider', 'updated_at')
    op.drop_column('provider', 'created_at')
    # ### end Alembic commands ###
