"""add_preferred_language_to_user

Revision ID: 3e903c99469a
Revises: 5305d4c52e22
Create Date: 2026-02-22 20:57:39.990166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e903c99469a'
down_revision: Union[str, Sequence[str], None] = '5305d4c52e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('preferred_language', sa.String(length=5), nullable=False, server_default='en'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'preferred_language')
    # ### end Alembic commands ###
