"""add_trip_amenities_refundability_meeting_place_and_extra_fees

Revision ID: 48043c0a50e5
Revises: 1b57a044cc51
Create Date: 2026-01-31 16:33:26.305752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '48043c0a50e5'
down_revision: Union[str, Sequence[str], None] = '1b57a044cc51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_extra_fees',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('trip_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=False),
    sa.Column('description_en', sa.String(length=500), nullable=True),
    sa.Column('description_ar', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_extra_fees_trip_id'), 'trip_extra_fees', ['trip_id'], unique=False)
    op.add_column('trip', sa.Column('is_refundable', sa.Boolean(), nullable=False))
    op.add_column('trip', sa.Column('amenities', sa.JSON(), nullable=True))
    op.add_column('trip', sa.Column('has_meeting_place', sa.Boolean(), nullable=False))
    op.add_column('trip', sa.Column('meeting_location', sa.String(length=500), nullable=True))
    op.add_column('trip', sa.Column('meeting_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip', 'meeting_time')
    op.drop_column('trip', 'meeting_location')
    op.drop_column('trip', 'has_meeting_place')
    op.drop_column('trip', 'amenities')
    op.drop_column('trip', 'is_refundable')
    op.drop_index(op.f('ix_trip_extra_fees_trip_id'), table_name='trip_extra_fees')
    op.drop_table('trip_extra_fees')
    # ### end Alembic commands ###
