"""add_validation_config_to_trip_package_required_field

Revision ID: 487459728ac9
Revises: bdbb7ce62432
Create Date: 2025-09-02 03:16:22.060998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '487459728ac9'
down_revision: Union[str, Sequence[str], None] = 'bdbb7ce62432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trippackagerequiredfield', sa.Column('validation_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trippackagerequiredfield', 'validation_config')
    # ### end Alembic commands ###
