"""add_booking_reference_and_trip_reference

Revision ID: 48fb3f371bc7
Revises: 273c654aef72
Create Date: 2026-02-22 01:03:43.983980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48fb3f371bc7'
down_revision: Union[str, Sequence[str], None] = '273c654aef72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('trip', sa.Column('trip_reference', sa.String(length=20), nullable=False, server_default='TRIP-LEGACY0'))
    op.create_index(op.f('ix_trip_trip_reference'), 'trip', ['trip_reference'], unique=False)
    op.add_column('tripregistration', sa.Column('booking_reference', sa.String(length=20), nullable=False, server_default='BOOK-LEGACY0'))
    op.create_index(op.f('ix_tripregistration_booking_reference'), 'tripregistration', ['booking_reference'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tripregistration_booking_reference'), table_name='tripregistration')
    op.drop_column('tripregistration', 'booking_reference')
    op.drop_index(op.f('ix_trip_trip_reference'), table_name='trip')
    op.drop_column('trip', 'trip_reference')
    # ### end Alembic commands ###
