"""add_registration_deadline_starting_city_is_international

Revision ID: 5305d4c52e22
Revises: 48fb3f371bc7
Create Date: 2026-02-22 01:41:03.308622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5305d4c52e22'
down_revision: Union[str, Sequence[str], None] = '48fb3f371bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('registration_deadline', sa.DateTime(), nullable=True))
    op.add_column('trip', sa.Column('starting_city_id', sa.Uuid(), nullable=True))
    op.add_column('trip', sa.Column('is_international', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_trip_is_international'), 'trip', ['is_international'], unique=False)
    op.create_index(op.f('ix_trip_registration_deadline'), 'trip', ['registration_deadline'], unique=False)
    op.create_index(op.f('ix_trip_starting_city_id'), 'trip', ['starting_city_id'], unique=False)
    op.create_foreign_key(None, 'trip', 'destinations', ['starting_city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.drop_index(op.f('ix_trip_starting_city_id'), table_name='trip')
    op.drop_index(op.f('ix_trip_registration_deadline'), table_name='trip')
    op.drop_index(op.f('ix_trip_is_international'), table_name='trip')
    op.drop_column('trip', 'is_international')
    op.drop_column('trip', 'starting_city_id')
    op.drop_column('trip', 'registration_deadline')
    # ### end Alembic commands ###
