"""make_bilingual_fields_optional

Revision ID: 5641ad16ce1c
Revises: e9fa94929987
Create Date: 2026-02-03 15:38:49.285216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5641ad16ce1c'
down_revision: Union[str, Sequence[str], None] = 'e9fa94929987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trip', 'name_en',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('trip', 'name_ar',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('trip', 'description_en',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('trip', 'description_ar',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('trippackage', 'name_en',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('trippackage', 'name_ar',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('trippackage', 'description_en',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('trippackage', 'description_ar',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trippackage', 'description_ar',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('trippackage', 'description_en',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('trippackage', 'name_ar',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('trippackage', 'name_en',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('trip', 'description_ar',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('trip', 'description_en',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('trip', 'name_ar',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('trip', 'name_en',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
