"""add_trip_update_tables

Revision ID: 5cb9c21916df
Revises: d1b7ed130aec
Create Date: 2026-02-09 00:28:53.446083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5cb9c21916df'
down_revision: Union[str, Sequence[str], None] = 'd1b7ed130aec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tripupdate',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('trip_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('provider_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('registration_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('is_important', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['tripregistration.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tripupdate_provider_id'), 'tripupdate', ['provider_id'], unique=False)
    op.create_index(op.f('ix_tripupdate_registration_id'), 'tripupdate', ['registration_id'], unique=False)
    op.create_index(op.f('ix_tripupdate_trip_id'), 'tripupdate', ['trip_id'], unique=False)
    op.create_table('tripupdatereceipt',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('update_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['update_id'], ['tripupdate.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tripupdatereceipt_update_id'), 'tripupdatereceipt', ['update_id'], unique=False)
    op.create_index(op.f('ix_tripupdatereceipt_user_id'), 'tripupdatereceipt', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tripupdatereceipt_user_id'), table_name='tripupdatereceipt')
    op.drop_index(op.f('ix_tripupdatereceipt_update_id'), table_name='tripupdatereceipt')
    op.drop_table('tripupdatereceipt')
    op.drop_index(op.f('ix_tripupdate_trip_id'), table_name='tripupdate')
    op.drop_index(op.f('ix_tripupdate_registration_id'), table_name='tripupdate')
    op.drop_index(op.f('ix_tripupdate_provider_id'), table_name='tripupdate')
    op.drop_table('tripupdate')
    # ### end Alembic commands ###
