"""add_file_definition_and_provider_file_tables

Revision ID: 5e2be6fd1785
Revises: 231716205940
Create Date: 2026-01-22 16:33:41.046296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '5e2be6fd1785'
down_revision: Union[str, Sequence[str], None] = '231716205940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filedefinition',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=False),
    sa.Column('description_en', sa.String(length=500), nullable=False),
    sa.Column('description_ar', sa.String(length=500), nullable=False),
    sa.Column('allowed_extensions', sa.JSON(), nullable=True),
    sa.Column('max_size_mb', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filedefinition_key'), 'filedefinition', ['key'], unique=True)
    op.create_table('providerfile',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('provider_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('file_definition_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('file_extension', sa.String(length=10), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_definition_id'], ['filedefinition.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providerfile_file_definition_id'), 'providerfile', ['file_definition_id'], unique=False)
    op.create_index(op.f('ix_providerfile_provider_id'), 'providerfile', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_providerfile_provider_id'), table_name='providerfile')
    op.drop_index(op.f('ix_providerfile_file_definition_id'), table_name='providerfile')
    op.drop_table('providerfile')
    op.drop_index(op.f('ix_filedefinition_key'), table_name='filedefinition')
    op.drop_table('filedefinition')
    # ### end Alembic commands ###
