"""add_per_person_package_selection

Revision ID: 6a21a3e89116
Revises: 59e7a69e545b
Create Date: 2025-08-22 05:11:19.889426

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a21a3e89116'
down_revision: Union[str, Sequence[str], None] = '59e7a69e545b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tripregistration', sa.Column('registration_date', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('tripregistration_package_id_fkey'), 'tripregistration', type_='foreignkey')
    op.drop_column('tripregistration', 'created_at')
    op.drop_column('tripregistration', 'updated_at')
    op.drop_column('tripregistration', 'package_id')
    op.add_column('tripregistrationparticipant', sa.Column('package_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('tripregistrationparticipant', sa.Column('additional_info', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'tripregistrationparticipant', 'trippackage', ['package_id'], ['id'])
    op.alter_column('triprequiredfield', 'field_type',
               existing_type=postgresql.ENUM('id_iqama_number', 'passport_number', 'name', 'phone', 'email', 'address', 'city', 'country', 'date_of_birth', 'gender', 'disability', 'medical_conditions', 'allergies', name='tripfieldtype'),
               nullable=True)
    op.alter_column('user', 'source',
               existing_type=postgresql.ENUM('mobile_app', 'admin_panel', 'providers_panel', name='requestsource'),
               nullable=True,
               existing_server_default=sa.text("'mobile_app'::requestsource"))
    op.drop_constraint(op.f('user_email_source_key'), 'user', type_='unique')
    op.drop_constraint(op.f('user_phone_source_key'), 'user', type_='unique')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_unique_constraint('unique_email_per_source', 'user', ['email', 'source'])
    op.create_unique_constraint('unique_phone_per_source', 'user', ['phone', 'source'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_phone_per_source', 'user', type_='unique')
    op.drop_constraint('unique_email_per_source', 'user', type_='unique')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_unique_constraint(op.f('user_phone_source_key'), 'user', ['phone', 'source'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('user_email_source_key'), 'user', ['email', 'source'], postgresql_nulls_not_distinct=False)
    op.alter_column('user', 'source',
               existing_type=postgresql.ENUM('mobile_app', 'admin_panel', 'providers_panel', name='requestsource'),
               nullable=False,
               existing_server_default=sa.text("'mobile_app'::requestsource"))
    op.alter_column('triprequiredfield', 'field_type',
               existing_type=postgresql.ENUM('id_iqama_number', 'passport_number', 'name', 'phone', 'email', 'address', 'city', 'country', 'date_of_birth', 'gender', 'disability', 'medical_conditions', 'allergies', name='tripfieldtype'),
               nullable=False)
    op.drop_constraint(None, 'tripregistrationparticipant', type_='foreignkey')
    op.drop_column('tripregistrationparticipant', 'additional_info')
    op.drop_column('tripregistrationparticipant', 'package_id')
    op.add_column('tripregistration', sa.Column('package_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('tripregistration', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.add_column('tripregistration', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('tripregistration_package_id_fkey'), 'tripregistration', 'trippackage', ['package_id'], ['id'])
    op.drop_column('tripregistration', 'registration_date')
    # ### end Alembic commands ###
