"""initial_schema

Revision ID: 7f9c4e05d00b
Revises: 
Create Date: 2026-02-23 21:58:53.982910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f9c4e05d00b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip', 'is_refundable')
    op.drop_column('trip', 'amenities')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('amenities', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('trip', sa.Column('is_refundable', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
