"""add_provider_rating_table

Revision ID: 97f14fb1e5f5
Revises: 5641ad16ce1c
Create Date: 2026-02-07 16:35:16.436735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '97f14fb1e5f5'
down_revision: Union[str, Sequence[str], None] = '5641ad16ce1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providerrating',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('provider_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider_id', name='unique_user_provider_rating')
    )
    op.create_index(op.f('ix_providerrating_provider_id'), 'providerrating', ['provider_id'], unique=False)
    op.create_index(op.f('ix_providerrating_user_id'), 'providerrating', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_providerrating_user_id'), table_name='providerrating')
    op.drop_index(op.f('ix_providerrating_provider_id'), table_name='providerrating')
    op.drop_table('providerrating')
    # ### end Alembic commands ###
