"""Add Provider model and user roles

Revision ID: 9b1b0a5d3d41
Revises: 80345ee59fbb
Create Date: 2025-08-18 00:23:30.067046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b1b0a5d3d41'
down_revision: Union[str, Sequence[str], None] = '80345ee59fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provider_request_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['provider_request_id'], ['providerrequest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_company_email'), 'provider', ['company_email'], unique=True)
    userrole = postgresql.ENUM('ADMIN', 'SUPER_ADMIN', 'PROVIDER', 'SUPER_PROVIDER', 'NORMAL', name='userrole', create_type=False)
    userrole.create(op.get_bind(), checkfirst=True)
    op.add_column('user', sa.Column('role', userrole, nullable=False, server_default='NORMAL'))
    op.add_column('user', sa.Column('provider_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'user', 'provider', ['provider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'provider_id')
    op.drop_column('user', 'role')
    op.execute('DROP TYPE userrole')
    op.drop_index(op.f('ix_provider_company_email'), table_name='provider')
    op.drop_table('provider')
    # ### end Alembic commands ###
