"""add_payments_table

Revision ID: a529f42af1f7
Revises: 9d0acebf018f
Create Date: 2026-01-31 15:48:35.478919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a529f42af1f7'
down_revision: Union[str, Sequence[str], None] = '9d0acebf018f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('moyasar_payment_id', sa.String(length=100), nullable=True),
    sa.Column('registration_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'PAID', 'FAILED', 'AUTHORIZED', 'CAPTURED', 'REFUNDED', 'VOIDED', name='paymentstatus'), nullable=False),
    sa.Column('payment_method', sa.Enum('CREDITCARD', 'APPLEPAY', 'STCPAY', 'MADA', name='paymentmethod'), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('callback_url', sa.String(length=500), nullable=True),
    sa.Column('refunded', sa.Boolean(), nullable=False),
    sa.Column('refunded_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('moyasar_metadata', sa.JSON(), nullable=True),
    sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['registration_id'], ['tripregistration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_moyasar_payment_id'), 'payments', ['moyasar_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_registration_id'), 'payments', ['registration_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_registration_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_moyasar_payment_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
