"""Add source column to user table

Revision ID: f1a2b3c4d5e6
Revises: 6b34d3014e27
Create Date: 2025-08-20 23:04:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a2b3c4d5e6'
down_revision = '6b34d3014e27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    op.execute("CREATE TYPE requestsource AS ENUM ('mobile_app', 'admin_panel', 'providers_panel')")
    
    # Add the source column with default value
    op.add_column('user', sa.Column('source', sa.Enum('mobile_app', 'admin_panel', 'providers_panel', name='requestsource'), nullable=False, server_default='mobile_app'))
    
    # Create new composite unique constraints (no existing unique constraints to drop)
    op.create_unique_constraint('user_email_source_key', 'user', ['email', 'source'])
    op.create_unique_constraint('user_phone_source_key', 'user', ['phone', 'source'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_phone_source_key', 'user', type_='unique')
    op.drop_constraint('user_email_source_key', 'user', type_='unique')
    op.drop_column('user', 'source')
    op.execute("DROP TYPE requestsource")
    op.create_unique_constraint('user_phone_key', 'user', ['phone'])
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    # ### end Alembic commands ###
