"""Remove TripRequiredField table - fields now managed at package level

Revision ID: bdbb7ce62432
Revises: 39ef452a6f14
Create Date: 2025-09-01 03:56:21.009001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bdbb7ce62432'
down_revision: Union[str, Sequence[str], None] = '39ef452a6f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('triprequiredfield')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triprequiredfield',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trip_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('field_type', postgresql.ENUM('id_iqama_number', 'passport_number', 'name', 'phone', 'email', 'address', 'city', 'country', 'date_of_birth', 'gender', 'disability', 'medical_conditions', 'allergies', name='tripfieldtype'), autoincrement=False, nullable=True),
    sa.Column('is_required', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], name=op.f('triprequiredfield_trip_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('triprequiredfield_pkey'))
    )
    # ### end Alembic commands ###
