"""add_destinations_places_trip_destinations

Revision ID: c45a70c18320
Revises: 97f14fb1e5f5
Create Date: 2026-02-07 19:23:42.599827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c45a70c18320'
down_revision: Union[str, Sequence[str], None] = '97f14fb1e5f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('type', sa.Enum('COUNTRY', 'CITY', name='destinationtype'), nullable=True),
    sa.Column('parent_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_ar', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('currency_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('google_place_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['destinations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_slug', name='unique_full_slug'),
    sa.UniqueConstraint('parent_id', 'slug', name='unique_parent_slug')
    )
    op.create_index(op.f('ix_destinations_country_code'), 'destinations', ['country_code'], unique=False)
    op.create_index(op.f('ix_destinations_is_active'), 'destinations', ['is_active'], unique=False)
    op.create_table('places',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('destination_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('type', sa.Enum('AREA', 'DISTRICT', 'ATTRACTION', 'RESORT', 'THEME_PARK', 'LANDMARK', 'EXPERIENCE', name='placetype'), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_ar', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('google_place_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destination_id', 'slug', name='unique_destination_place_slug')
    )
    op.create_index(op.f('ix_places_destination_id'), 'places', ['destination_id'], unique=False)
    op.create_table('trip_destinations',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('trip_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('destination_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('place_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'destination_id', name='unique_trip_destination')
    )
    op.create_index(op.f('ix_trip_destinations_destination_id'), 'trip_destinations', ['destination_id'], unique=False)
    op.create_index(op.f('ix_trip_destinations_trip_id'), 'trip_destinations', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_destinations_trip_id'), table_name='trip_destinations')
    op.drop_index(op.f('ix_trip_destinations_destination_id'), table_name='trip_destinations')
    op.drop_table('trip_destinations')
    op.drop_index(op.f('ix_places_destination_id'), table_name='places')
    op.drop_table('places')
    op.drop_index(op.f('ix_destinations_is_active'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_country_code'), table_name='destinations')
    op.drop_table('destinations')
    # ### end Alembic commands ###
