"""add_support_ticket_tables

Revision ID: d1b7ed130aec
Revises: c45a70c18320
Create Date: 2026-02-08 23:49:28.313047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd1b7ed130aec'
down_revision: Union[str, Sequence[str], None] = 'c45a70c18320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supportticket',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sa.Enum('TECHNICAL', 'BILLING', 'GENERAL', name='ticketcategory'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='ticketpriority'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'WAITING_ON_USER', 'RESOLVED', 'CLOSED', name='ticketstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supportticket_status'), 'supportticket', ['status'], unique=False)
    op.create_index(op.f('ix_supportticket_user_id'), 'supportticket', ['user_id'], unique=False)
    op.create_table('tripsupportticket',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('provider_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('trip_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('registration_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'WAITING_ON_USER', 'RESOLVED', 'CLOSED', name='ticketstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='ticketpriority'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['tripregistration.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tripsupportticket_provider_id'), 'tripsupportticket', ['provider_id'], unique=False)
    op.create_index(op.f('ix_tripsupportticket_registration_id'), 'tripsupportticket', ['registration_id'], unique=False)
    op.create_index(op.f('ix_tripsupportticket_status'), 'tripsupportticket', ['status'], unique=False)
    op.create_index(op.f('ix_tripsupportticket_trip_id'), 'tripsupportticket', ['trip_id'], unique=False)
    op.create_index(op.f('ix_tripsupportticket_user_id'), 'tripsupportticket', ['user_id'], unique=False)
    op.create_table('ticketmessage',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('support_ticket_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('trip_support_ticket_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('sender_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('sender_type', sa.Enum('USER', 'ADMIN', 'PROVIDER', name='sendertype'), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['support_ticket_id'], ['supportticket.id'], ),
    sa.ForeignKeyConstraint(['trip_support_ticket_id'], ['tripsupportticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticketmessage_support_ticket_id'), 'ticketmessage', ['support_ticket_id'], unique=False)
    op.create_index(op.f('ix_ticketmessage_trip_support_ticket_id'), 'ticketmessage', ['trip_support_ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticketmessage_trip_support_ticket_id'), table_name='ticketmessage')
    op.drop_index(op.f('ix_ticketmessage_support_ticket_id'), table_name='ticketmessage')
    op.drop_table('ticketmessage')
    op.drop_index(op.f('ix_tripsupportticket_user_id'), table_name='tripsupportticket')
    op.drop_index(op.f('ix_tripsupportticket_trip_id'), table_name='tripsupportticket')
    op.drop_index(op.f('ix_tripsupportticket_status'), table_name='tripsupportticket')
    op.drop_index(op.f('ix_tripsupportticket_registration_id'), table_name='tripsupportticket')
    op.drop_index(op.f('ix_tripsupportticket_provider_id'), table_name='tripsupportticket')
    op.drop_table('tripsupportticket')
    op.drop_index(op.f('ix_supportticket_user_id'), table_name='supportticket')
    op.drop_index(op.f('ix_supportticket_status'), table_name='supportticket')
    op.drop_table('supportticket')
    # ### end Alembic commands ###
