"""update_bilingual_fields_trip_package_provider

Revision ID: e9fa94929987
Revises: 3d66ce366c29
Create Date: 2026-02-01 23:11:06.937028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9fa94929987'
down_revision: Union[str, Sequence[str], None] = '3d66ce366c29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add bilingual fields to provider (nullable, so no data migration needed)
    op.add_column('provider', sa.Column('bio_en', sa.String(length=1000), nullable=True))
    op.add_column('provider', sa.Column('bio_ar', sa.String(length=1000), nullable=True))
    
    # Add bilingual fields to trip (nullable first to allow data migration)
    op.add_column('trip', sa.Column('name_en', sa.String(length=200), nullable=True))
    op.add_column('trip', sa.Column('name_ar', sa.String(length=200), nullable=True))
    op.add_column('trip', sa.Column('description_en', sa.String(), nullable=True))
    op.add_column('trip', sa.Column('description_ar', sa.String(), nullable=True))
    
    # Migrate existing trip data to both languages
    op.execute("UPDATE trip SET name_en = name, name_ar = name WHERE name IS NOT NULL")
    op.execute("UPDATE trip SET description_en = description, description_ar = description WHERE description IS NOT NULL")
    
    # Make new columns non-nullable
    op.alter_column('trip', 'name_en', nullable=False)
    op.alter_column('trip', 'name_ar', nullable=False)
    op.alter_column('trip', 'description_en', nullable=False)
    op.alter_column('trip', 'description_ar', nullable=False)
    
    # Drop old columns
    op.drop_column('trip', 'description')
    op.drop_column('trip', 'name')
    
    # Add bilingual fields to trippackage (nullable first)
    op.add_column('trippackage', sa.Column('name_en', sa.String(length=150), nullable=True))
    op.add_column('trippackage', sa.Column('name_ar', sa.String(length=150), nullable=True))
    op.add_column('trippackage', sa.Column('description_en', sa.String(), nullable=True))
    op.add_column('trippackage', sa.Column('description_ar', sa.String(), nullable=True))
    
    # Migrate existing package data to both languages
    op.execute("UPDATE trippackage SET name_en = name, name_ar = name WHERE name IS NOT NULL")
    op.execute("UPDATE trippackage SET description_en = description, description_ar = description WHERE description IS NOT NULL")
    
    # Make new columns non-nullable
    op.alter_column('trippackage', 'name_en', nullable=False)
    op.alter_column('trippackage', 'name_ar', nullable=False)
    op.alter_column('trippackage', 'description_en', nullable=False)
    op.alter_column('trippackage', 'description_ar', nullable=False)
    
    # Drop old columns
    op.drop_column('trippackage', 'description')
    op.drop_column('trippackage', 'name')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trippackage', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('trippackage', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('trippackage', 'description_ar')
    op.drop_column('trippackage', 'description_en')
    op.drop_column('trippackage', 'name_ar')
    op.drop_column('trippackage', 'name_en')
    op.add_column('trip', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('trip', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('trip', 'description_ar')
    op.drop_column('trip', 'description_en')
    op.drop_column('trip', 'name_ar')
    op.drop_column('trip', 'name_en')
    op.drop_column('provider', 'bio_ar')
    op.drop_column('provider', 'bio_en')
    # ### end Alembic commands ###
