"""Add user verification columns

Revision ID: g7h8i9j0k1l2
Revises: f1a2b3c4d5e6
Create Date: 2025-08-22 04:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'g7h8i9j0k1l2'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_phone_verified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user', sa.Column('is_email_verified', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_email_verified')
    op.drop_column('user', 'is_phone_verified')
    # ### end Alembic commands ###
